### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by ofim26** [glebbash/nestjs-fireorm#10]
How to solve this dependency resolution error?

![Captura de pantalla 2023-05-03 a la(s) 15 34 43](https://user-images.githubusercontent.com/5898215/236026312-fc0fa1ed-5a76-4e61-9cf6-ae7d2386957b.png)

**Comment by glebbash** [comment]
It is hard to say what went wrong here without more info.

You might be missing:

```ts
@Module({
  imports: [FireormModule.forFeature([User])],
})
export class AppModule {}
```

or 

```ts
@InjectRepository(User)
private users: BaseFirestoreRepository<User>
```

**Comment by glebbash** [comment]
Closing this as stale, feel free to create another issue with more info if you still need help.
