### ISSUE TITLE
Can't use async function with forRootAsync

### ISSUE THREAD

**Issue by tttmaximttt** [glebbash/nestjs-fireorm#7]
` Type 'Promise<FireormSettings>' is not assignable to type 'FireormSettings'.
useFactory: async (configService: ConfigService, utils: Utils): Promise<FireormSettings> => {`

![Screenshot 2023-02-22 at 11 36 08](https://user-images.githubusercontent.com/8621125/220597509-ed03830d-02fe-4a6d-ac42-02f47616aa32.png)

**Comment by glebbash** [comment]
Works fine for me, are you using the latest `@nestjs/common` version?
![image](https://user-images.githubusercontent.com/17786588/220603851-cee46570-21a9-4d36-81ad-a5de3125021a.png)

**Comment by tttmaximttt** [comment]
^8.0.0 I will try to update up to 9, thanks
