### ISSUE TITLE
question: can I have auto generated fields like createdAt, updatedAt

### ISSUE THREAD

**Issue by tttmaximttt** [glebbash/nestjs-fireorm#8]
question: can I have auto generated fields like createdAt, updatedAt

**Comment by glebbash** [comment]
This lib is only a wrapper for [FireORM](https://github.com/wovalle/fireorm). They have this feature in wishlist section in their [roadmap](https://github.com/wovalle/fireorm/issues/1).

It should be possible to automatically set `updatedAt` / `createdAt` with cloud functions, [check here](https://stackoverflow.com/questions/53558407/how-can-i-keep-track-of-the-last-updated-at-time-for-a-document-in-firestore).

But it's probably an overkill and it will be easier to just do it from code.
