### ISSUE TITLE
Error: Firestore must be initialized first - on using customRepository

### ISSUE THREAD

**Issue by nagapriyanka** [glebbash/nestjs-fireorm#9]
Using nestjs-fireorm, I am facing this below issue while creating a customRepository which extends on BaseFirestoreRepository

Error: Firestore must be initialized first
at userCustomRepository.AbstractFirestoreRepository [as constructor] firestore_fireorm\node_modules**\fireorm\lib\src\AbstractFirestoreRepository.js:159:19)**

`import { BaseFirestoreRepository, CustomRepository } from 'fireorm';
import { User } from '../entities/user.entity';

@CustomRepository(User)
export class userCustomRepository extends BaseFirestoreRepository{`
It's not working as expected, Referred official Document : [https://fireorm.js.org/#/Custom_Repositories](https://github.com/wovalle/fireorm/issues/url)

Files Attached for reference below.
![customRepo_gitIssue](https://user-images.githubusercontent.com/22192381/226301485-3a494fad-0341-46d2-b432-3496ed6c1bf4.PNG)
![FireormcustomRepo_err](https://user-images.githubusercontent.com/22192381/226301495-9bae2d00-1285-4257-983a-5a993baa5111.PNG)

@shaswatsaxena 
Can you help on this

**Comment by glebbash** [comment]
Extending `BaseFirestoreRepository` is not supported.

Instead you should inject and use it directly in the service like this:

```ts

@Module({
  imports: [FireormModule.forFeature([User])],
  providers: [UsersService],
})
export class UsersModule {}

@Injectable()
export class UsersService {
  constructor(
    @InjectRepository(User)
    private users: BaseFirestoreRepository<User>
  ) {}

  async findOne(id: string): Promise<User> {
    return await this.users.findById(id);
  }
}
```

Check [example setup here](https://github.com/glebbash/nestjs-fireorm/tree/master/example/src/users)

**Comment by Bishal18** [comment]
> Extending `BaseFirestoreRepository` is not supported.
> 
> Instead you should inject and use it directly in the service like this:
> 
> ```ts
> @Module({
>   imports: [FireormModule.forFeature([User])],
>   providers: [UsersService],
> })
> export class UsersModule {}
> 
> @Injectable()
> export class UsersService {
>   constructor(
>     @InjectRepository(User)
>     private users: BaseFirestoreRepository<User>
>   ) {}
> 
>   async findOne(id: string): Promise<User> {
>     return await this.users.findById(id);
>   }
> }
> ```
> 
> Check [example setup here](https://github.com/glebbash/nestjs-fireorm/tree/master/example/src/users)

Hi @glebbash , 
The whole intention of using a custom repository was to create and follow the repository layer where we implement our own abstracted custom repo layers with our own methods which ultimately calls the fireorm methods internally. I hope you will anyways be aware of the benefits of following such a pattern. Hence the ask whether custom repsoitories will be supported as it is a concept of fireorm itself and built for this purpose.

For now anyways we have kept a repository layer where the fireorm repo is manually injected like you have given the example for a service, but not sure if this is the better way to do it.

**Comment by glebbash** [comment]
You can still create a custom repository using composition instead of inheritence.

```ts
@Injectable()
export class UsersRepository {
  constructor(
    @InjectRepository(User)
    private base: BaseFirestoreRepository<User>
  ) {}

  async findById(id: string): Promise<User> {
    return await this.base.findById(id);
  }
}
```

There is no easy way to support [custom repositories](https://fireorm.js.org/#/Custom_Repositories) because fireorm has it's own dependency injection logic and you basically won't be able to @Inject() anything into your custom repository.

**Comment by glebbash** [comment]
Closing this as stale, feel free to create another issue with more info (or tag me to reopen this one) if you still need help.
